### ISSUE TITLE
Save Tournament 2.0

### ISSUE THREAD

**Issue by NumyaOrion** [recke96/HemaTournament#40] opened 2023-07-14 09:38 UTC
•	the tournament is saved with an entered name and date
•	the system saves the results of all single fights in the tournament arranged by rounds (names of the fighters, points and double hits)
•	for every fencer his overall points (scored and received points apart), amount of fights, wins, losses, draws, double hits and final CUT is saved

**Comment by recke96** [comment] 2023-07-14 12:03
Duplicate of #27

**Closed by recke96** 2023-07-14 12:03 UTC
